app/urls.py
from django.urls import path

from app import views

app_name = 'app'


urlpatterns = [
    path('', views.AppList.as_view(), name='list'),
    path('detail/<int:pk>/', views.AppDetail.as_view(), name='detail'),
    path('update/<int:app_id>/', views.instant_update, name='update'),
    path('update-all/', views.instant_update_all, name='update-all'),
    path('chart/<int:app_id>/<str:name>/', views.ValuesJSONView.as_view(), name='chart'),
]

app_monitor/urls.py
from allauth.account.decorators import secure_admin_login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView


admin.autodiscover()
admin.site.site_header = _('Django App Monitor')
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', RedirectView.as_view(url='/', permanent=True)),
    path('accounts/', include('allauth.urls')),
    path('app/', include('app.urls')),
    path('', RedirectView.as_view(pattern_name='app:list', permanent=False), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/application_detail.html
{% extends "base.html" %}
{% load i18n static django_bootstrap5 bootstrap_icons humanize app_tags %}

{% block bootstrap5_extra_head %}
{{ block.super }}
<link rel="stylesheet" href="{% static "app/css/style.css" %}">
{% endblock %}

{% block bootstrap5_extra_script %}
{{ block.super }}
{% if application.use_metrics %}
<script type="text/javascript" src="{% static 'app_monitor/js/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'app/chartjs/chart.umd.js' %}"></script>
<script type="text/javascript">
{% for value in value_names %}
    $.get('{% url "app:chart" application.id value.0 %}', function(data) {
        const {{ value.0 }}_ctx = document.getElementById('{{ value.0 }}_chart');
        new Chart({{ value.0 }}_ctx, {
            type: 'line',
            data: data,
            options: {
                plugins: {
                    legend: {
                        display: false
                    }
                },
                responsiv: true,
                scales: {
                    y: {
                        title: {
                            display: true,
                            text: '{{ value.1 }}'
                        },
                    }
                }
            }
        });
    });
{% endfor %}
</script>
{% endif %}
{% endblock %}

{% block page_title %}Status {{ application.name }}{% endblock %}

{% block content %}
<h6 class="text-center mb-3">
    <a href="{% url 'app:update' application.id %}" title="{% trans 'Go to' %} {{ app.name }}">
        {% bs_icon 'arrow-clockwise' %}
    </a>
    Letzte Aktualisierung: {{ application.last_update }}
    <a href="{{ application.url }}" target="_blank" title="{% trans 'Go to' %} {{ app.name }}">
        {% bs_icon 'box-arrow-up-right' %}
    </a>
</h6>
<div class="row row-cols-1 g-3">
    <div class="card-group">
        <div class="card text-center border-{% http_status_color application.http_status %}">
            <div class="card-header">
                <h5 class="mt-2">{% trans 'HTTP Status' %}</h5>
            </div>
            <div class="card-body">
                <p class="mb-1">
                    {{ application.http_status }}
                    <span class="badge text-bg-{% http_status_color application.http_status %}">
                        {{ application.get_http_status_text }}
                    </span>
                </p>
            </div>
        </div>
    </div>
</div>

{% if application.health_check %}
<h4 class="text-center mt-5">{% trans 'Health Check' %}</h4>
<div class="row row-cols-1 row-cols-md-2 g-3">
    {% for key, value in application.health_check.items %}
    <div class="col">
        <div class="card text-center border-{% health_check_color value %} h-100">
            <div class="card-header">
                <h5 class="mt-2">{{ key }}</h5>
            </div>
            <div class="card-body">
                <p class="mb-1">
                    {% for key, value in value.items %}
                        {% if key != 'status' %}
                            <strong>{{ key }}:</strong> {{ value }}<br>
                        {% endif %}
                    {% endfor %}
                </p>
                <p class="mb-1">
                    <span class="badge text-bg-{% health_check_color value %}">
                        {{ value.status }}
                    </span>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

{% if application.use_metrics %}
<h4 class="text-center mt-5">{% trans 'System metrics' %}</h4>
<div class="row row-cols-1 row-cols-md-2 g-3 mb-3">
    {% for value in value_names %}
    <div class="col">
        {% metrics_color application value.0 as color %}
        <div class="card text-center border-{{ color }}">
        <div class="card-header">
                <h5 class="mt-2">
                    {{ value.0|label }}
                    {% metrics_icon application value.0 as icon %}
                    {% if icon %}
                    <span class="text-{{ color }}">{% bs_icon icon %}</span>
                    {% endif %}
                </h5>
                <small>
                    {% trans 'Last' %}
                    {{ application.metric_days_in_hours }}
                    {% trans 'hours' %}
                </small>
            </div>
            <div class="card-body">
                <canvas id="{{ value.0 }}_chart" width="600" height="200"></canvas>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

{% if application.alerts.count > 0 %}
<h4 class="text-center mt-5">{% trans 'Alerts' %}</h4>
<div class="row row-cols-1 g-3">
    <div class="card-group">
        <div class="card border-default p-3">
            <table class="table table-sm table-striped">
                <thead>
                    <tr>
                        <th>{% trans 'Timestamp' %}</th>
                        <th>{% trans 'Type' %}</th>
                        <th>{% trans 'Value' %}</th>
                    </tr>
                </thead>
                <tbody>
                {% for alert in application.alerts.all %}
                    <tr>
                        <td>{{ alert.timestamp }}</td>
                        <td>{{ alert.typus }}</td>
                        <td>{{ alert.value }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/app/application_list.html
{% extends "base.html" %}
{% load i18n static django_bootstrap5 bootstrap_icons humanize app_tags %}

{% block bootstrap5_extra_head %}
{{ block.super }}
<link rel="stylesheet" href="{% static "app/css/style.css" %}">
{% endblock %}

{% block bootstrap5_extra_script %}
{{ block.super }}
{% endblock %}

{% block page_title %}{% trans "Applications" %}{% endblock %}


{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4 g-4">
{% for app in application_list %}
    <div class="card-group">
        <div class="card text-center">
            <div class="card-header text-center">
                <h5 class="mb-0">
                    {{ app.name }}
                    <a href="{{ app.url }}" target="_blank" title="{% trans 'Go to' %} {{ app.name }}">
                        {% bs_icon 'box-arrow-up-right' %}
                    </a>
                    <a href="{{ app.get_absolute_url }}" title="{% trans 'Go to' %} {{ app.name }}" class="float-end">
                        {% bs_icon 'clipboard-data' %}
                    </a>
                </h5>
            </div>
            <div>
                {% if app.logo %}
                <img class="card-img-top" src="{{ app.logo.url }}" alt="{{ app.name }}">
                {% else %}
                <img class="card-img-top" src="{% static 'app/img/app.png' %}" alt="{{ app.name }}">
                {% endif %}
            </div>
            <div class="card-body text-center">
                <div class="status {% if app.http_status == 200 %}text-bg-success{% else %}text-bg-danger{% endif %}">
                    Status: {{ app.http_status }} {{ app.get_http_status_text }}
                </div>
                {% if app.use_health_check %}
                <p class="mt-2">
                {% for key, value in app.health_check.items %}
                    {% is_ok value as ok %}
                    <span class="badge {% if ok %}text-bg-success{% else %}text-bg-danger{% endif %}">
                        {{ key }}
                    </span>
                {% endfor %}
                </p>
                {% endif %}
            </div>
            <div class="card-footer">
                <a href="{% url 'app:update' app.id %}" title="{% trans 'Go to' %} {{ app.name }}" class="float-start">
                    {% bs_icon 'arrow-clockwise' %}
                </a>
                <small class="text-muted">
                    {% trans 'Updated' %}
                    {{ app.last_update|naturaltime }}
                </small>
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% if request.user.is_superuser %}
<div class="row mt-3">
    <div class="col">
        <a class="btn btn-secondary" href="{% url 'app:update-all' %}">
            {% bs_icon 'arrow-clockwise' %}
        </a>
    </div>
</div>
{% endif %}

{% endblock %}